FROM microsoft/dotnet:2.2-sdk

WORKDIR /

COPY /HostOcean.Api/HostOcean.Api.csproj /src/HostOcean.Api/
COPY /HostOcean.Infrastructure/HostOcean.Infrastructure.csproj /src/HostOcean.Infrastructure/

RUN dotnet restore /src/HostOcean.Api/HostOcean.Api.csproj

COPY . /src

RUN dotnet build /src/HostOcean.Api/HostOcean.Api.csproj -c Release

RUN dotnet publish /src/HostOcean.Api/HostOcean.Api.csproj -c Release -o /app

